"""initial

Revision ID: 7a3d57024e18
Revises: 
Create Date: 2026-05-14 17:42:14.586788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a3d57024e18'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('professor', 'mestre', 'admin', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_table('user_rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'room_id', name='uq_user_room')
    )
    op.create_table('actuation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('lamp_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('on', 'off', name='lampaction'), nullable=False),
    sa.Column('energy_kwh', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['lamp_id'], ['lamps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actuation_logs_created_at'), 'actuation_logs', ['created_at'], unique=False)
    op.drop_index(op.f('ix_iot_events_id'), table_name='iot_events')
    op.drop_table('iot_events')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_table('loja')
    op.drop_index(op.f('ix_energy_logs_id'), table_name='energy_logs')
    op.drop_table('energy_logs')
    op.add_column('lamps', sa.Column('slot', sa.Integer(), nullable=False))
    op.add_column('lamps', sa.Column('last_on_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('lamps', 'power_watts',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('lamps', 'is_on',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_lamps_id'), table_name='lamps')
    op.drop_constraint(op.f('lamps_room_id_fkey'), 'lamps', type_='foreignkey')
    op.create_foreign_key(None, 'lamps', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_column('lamps', 'is_active')
    op.drop_column('lamps', 'created_at')
    op.drop_column('lamps', 'turned_on_at')
    op.drop_column('lamps', 'energy_consumption')
    op.drop_column('lamps', 'updated_at')
    op.add_column('rooms', sa.Column('code', sa.String(length=64), nullable=False))
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_constraint(op.f('rooms_name_key'), 'rooms', type_='unique')
    op.create_index(op.f('ix_rooms_code'), 'rooms', ['code'], unique=False)
    op.create_unique_constraint('uq_rooms_code', 'rooms', ['code'])
    op.drop_column('rooms', 'description')
    op.drop_column('rooms', 'is_active')
    op.drop_column('rooms', 'presence_detected')
    op.drop_column('rooms', 'current_people')
    op.drop_column('rooms', 'capacity')
    op.drop_column('rooms', 'created_at')
    op.drop_column('rooms', 'floor')
    op.drop_column('rooms', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('floor', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('rooms', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('current_people', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('presence_detected', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_rooms_code', 'rooms', type_='unique')
    op.drop_index(op.f('ix_rooms_code'), table_name='rooms')
    op.create_unique_constraint(op.f('rooms_name_key'), 'rooms', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.drop_column('rooms', 'code')
    op.add_column('lamps', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('lamps', sa.Column('energy_consumption', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('lamps', sa.Column('turned_on_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('lamps', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('lamps', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lamps', type_='foreignkey')
    op.create_foreign_key(op.f('lamps_room_id_fkey'), 'lamps', 'rooms', ['room_id'], ['id'])
    op.create_index(op.f('ix_lamps_id'), 'lamps', ['id'], unique=False)
    op.alter_column('lamps', 'is_on',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('lamps', 'power_watts',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('lamps', 'last_on_at')
    op.drop_column('lamps', 'slot')
    op.create_table('energy_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('consumption_kwh', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('voltage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('current', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('power', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('lamp_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lamp_id'], ['lamps.id'], name=op.f('fk_energy_logs_lamp_id_lamps')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('energy_logs_room_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('energy_logs_pkey'))
    )
    op.create_index(op.f('ix_energy_logs_id'), 'energy_logs', ['id'], unique=False)
    op.create_table('loja',
    sa.Column('local', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('faturamento', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True)
    )
    op.create_table('devices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('device_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mac_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('firmware_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('devices_room_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('devices_pkey'))
    )
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entity', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('iot_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sensor_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sensor_value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('processed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('iot_events_device_id_fkey')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('iot_events_room_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('iot_events_pkey'))
    )
    op.create_index(op.f('ix_iot_events_id'), 'iot_events', ['id'], unique=False)
    op.drop_index(op.f('ix_actuation_logs_created_at'), table_name='actuation_logs')
    op.drop_table('actuation_logs')
    op.drop_table('user_rooms')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
