"""add logs tables

Revision ID: 741cf60c0f1d
Revises: 470206a10d58
Create Date: 2026-05-13 17:39:47.338621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '741cf60c0f1d'
down_revision: Union[str, Sequence[str], None] = '470206a10d58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('energy_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('consumption_kwh', sa.Float(), nullable=False),
    sa.Column('voltage', sa.Float(), nullable=True),
    sa.Column('current', sa.Float(), nullable=True),
    sa.Column('power', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_records_id'), 'energy_records', ['id'], unique=False)
    op.create_table('iot_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('sensor_name', sa.String(), nullable=True),
    sa.Column('sensor_value', sa.String(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iot_events_id'), 'iot_events', ['id'], unique=False)
    op.add_column('devices', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('devices', sa.Column('ip_address', sa.String(), nullable=True))
    op.add_column('devices', sa.Column('mac_address', sa.String(), nullable=True))
    op.add_column('devices', sa.Column('firmware_version', sa.String(), nullable=True))
    op.add_column('devices', sa.Column('last_temperature', sa.Float(), nullable=True))
    op.add_column('devices', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('devices', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('devices', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('energy_logs', sa.Column('device_id', sa.Integer(), nullable=True))
    op.add_column('energy_logs', sa.Column('voltage', sa.Float(), nullable=True))
    op.add_column('energy_logs', sa.Column('current', sa.Float(), nullable=True))
    op.add_column('energy_logs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('energy_logs', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'energy_logs', 'devices', ['device_id'], ['id'])
    op.drop_column('energy_logs', 'recorded_at')
    op.add_column('lamps', sa.Column('power_watts', sa.Float(), nullable=True))
    op.add_column('lamps', sa.Column('energy_consumption', sa.Float(), nullable=True))
    op.add_column('lamps', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('lamps', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('lamps', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('lamps', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('rooms', sa.Column('description', sa.String(), nullable=True))
    op.add_column('rooms', sa.Column('floor', sa.Integer(), nullable=False))
    op.add_column('rooms', sa.Column('capacity', sa.Integer(), nullable=True))
    op.add_column('rooms', sa.Column('current_people', sa.Integer(), nullable=True))
    op.add_column('rooms', sa.Column('presence_detected', sa.Boolean(), nullable=True))
    op.add_column('rooms', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('rooms', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('rooms', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'rooms', ['name'])
    op.drop_column('rooms', 'block')
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.drop_column('users', 'role')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_admin')
    op.add_column('rooms', sa.Column('block', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'rooms', type_='unique')
    op.drop_column('rooms', 'updated_at')
    op.drop_column('rooms', 'created_at')
    op.drop_column('rooms', 'is_active')
    op.drop_column('rooms', 'presence_detected')
    op.drop_column('rooms', 'current_people')
    op.drop_column('rooms', 'capacity')
    op.drop_column('rooms', 'floor')
    op.drop_column('rooms', 'description')
    op.alter_column('lamps', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('lamps', 'updated_at')
    op.drop_column('lamps', 'created_at')
    op.drop_column('lamps', 'is_active')
    op.drop_column('lamps', 'energy_consumption')
    op.drop_column('lamps', 'power_watts')
    op.add_column('energy_logs', sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'energy_logs', type_='foreignkey')
    op.alter_column('energy_logs', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('energy_logs', 'created_at')
    op.drop_column('energy_logs', 'current')
    op.drop_column('energy_logs', 'voltage')
    op.drop_column('energy_logs', 'device_id')
    op.alter_column('devices', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('devices', 'updated_at')
    op.drop_column('devices', 'created_at')
    op.drop_column('devices', 'last_temperature')
    op.drop_column('devices', 'firmware_version')
    op.drop_column('devices', 'mac_address')
    op.drop_column('devices', 'ip_address')
    op.drop_column('devices', 'is_active')
    op.drop_index(op.f('ix_iot_events_id'), table_name='iot_events')
    op.drop_table('iot_events')
    op.drop_index(op.f('ix_energy_records_id'), table_name='energy_records')
    op.drop_table('energy_records')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
