"""rename energy_records to energy_logs

Revision ID: 90370a6e350f
Revises: 50a07c78c155
Create Date: 2026-05-13 17:50:48.222423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90370a6e350f'
down_revision: Union[str, Sequence[str], None] = '50a07c78c155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_energy_records_id'), table_name='energy_records')
    op.drop_table('energy_records')
    op.add_column('energy_logs', sa.Column('power', sa.Float(), nullable=True))
    op.add_column('energy_logs', sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint(op.f('energy_logs_device_id_fkey'), 'energy_logs', type_='foreignkey')
    op.drop_column('energy_logs', 'device_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('energy_logs', sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('energy_logs_device_id_fkey'), 'energy_logs', 'devices', ['device_id'], ['id'])
    op.drop_column('energy_logs', 'recorded_at')
    op.drop_column('energy_logs', 'power')
    op.create_table('energy_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('consumption_kwh', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('voltage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('current', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('power', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('energy_records_room_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('energy_records_pkey'))
    )
    op.create_index(op.f('ix_energy_records_id'), 'energy_records', ['id'], unique=False)
    # ### end Alembic commands ###
